/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    container: {
      center: true,
      padding: "1rem",
    },
    extend: {
      fontFamily: {
        sans: ["Rubik", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Rubik", "ui-sans-serif", "system-ui", "sans-serif"],
        handwriting: ['"Gveret Levin"', "Rubik", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        sage: "hsl(var(--sage))",
        "sage-foreground": "hsl(var(--sage-foreground))",
        sky: "hsl(var(--sky))",
        "sky-foreground": "hsl(var(--sky-foreground))",
        coral: "hsl(var(--coral))",
        "coral-foreground": "hsl(var(--coral-foreground))",
        lavender: "hsl(var(--lavender))",
        "lavender-foreground": "hsl(var(--lavender-foreground))",
        rose: "hsl(var(--rose))",
        "rose-foreground": "hsl(var(--rose-foreground))",
        butter: "hsl(var(--butter))",
        "butter-foreground": "hsl(var(--butter-foreground))",
        cream: "hsl(var(--cream))",
        warm: "hsl(var(--warm))",
      },
      borderRadius: {
        sm: "calc(var(--radius) - 6px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 6px)",
        "2xl": "calc(var(--radius) + 14px)",
        "3xl": "calc(var(--radius) + 22px)",
      },
    },
  },
  plugins: [],
};
